#ifndef STATE_MANAGER_H
#define STATE_MANAGER_H

#include <stdint.h>
#include <stdbool.h>
#include "os_abstraction.h"

// System events generated by the hardware layer (Buttons, Timers)
typedef enum {
    EV_BTN_ALARM_PRESSED,
    EV_BTN_ALARM_RELEASED,
    EV_BTN_DIGIT_PRESSED,
    EV_BTN_DIGIT_RELEASED,
    EV_SYS_TICK_MINUTE
} StateEvent_t;

// Main state manager task entry point
extern void state_manager_task(RtosQueueHandle_t event_queue, RtosQueueHandle_t display_queue);

#endif // STATE_MANAGER_H

