#ifndef STATE_MANAGER_H
#define STATE_MANAGER_H

#include <stdint.h>
#include <stdbool.h>
#include "os_abstraction.h"

// System events generated by the hardware layer (Buttons, Timers) and handled by the state manager
typedef enum {
    EVENT_BUTTON_ALARM_PRESSED,
    EVENT_BUTTON_ALARM_RELEASED,
    EVENT_BUTTON_DIGIT_PRESSED,
    EVENT_BUTTON_DIGIT_RELEASED,
    EVENT_SYS_TICK_MINUTE
} StateEvent_t;

typedef struct {
    StateEvent_t event;
} StateMsg_t;


extern RtosQueueHandle_t state_message_queue;

// Main state manager task entry point
extern void state_manager_task(void);
extern void state_manager_process_event(StateMsg_t *msg);

#endif // STATE_MANAGER_H

